# 프로미스 정리
프로미스에 대해 알기전 Promise의 특징을 간단하게 보고 넘어 갑시다!

1. 일단 new Promise()로 생성된 변수를 콘솔창에 출력해보시면 현재 상태를 알 수 있습니다. 
성공/실패 판정 전에는 pending 이라고 나오며 </br>
성공 후엔  resolved </br>
실패 후엔 rejected 이런 식으로 나옵니다. </br>
이렇게 프로미스 오브젝트들은 3개 상태가 있습니다. 그리고 성공을 실패나 대기상태로 다시 되돌릴 순 없습니다.

2. Promise는 동기를 비동기로 만들어주는 코드가 아닙니다. 
Promise는 비동기적 실행과 전혀 상관이 없습니다.</br>
그냥 코딩을 예쁘게 할 수 있는 일종의 디자인 패턴입니다.</br>
예를 들면.. Promise 안에 10초 걸리는 어려운 연산을 시키면 10초동안 브라우저가 멈춥니다.</br>
10초 걸리는 연산을 해결될 때 까지 대기실에 제껴두고 그런거 아닙니다.</br> 


## 1. 프로미스
프로미스는 콜백대신 가독성 좋은 코드를 작성할수 있으며 성공, 실패의 경우에 맞춰 각각 다른 코드 실행이 가능합니다. </br>
아래 예제 코드는 프로미스를 만드는 가장 기본적인 틀입니다.
```jsx
const promiseTest = new Promise((resolve, reject)=>{
    resolve() // 성공하면
    reject()  // 실패하면
});  
// 프로미스는 성공했을때와 실패했을 때를 판단하는 함수라고 생각하기

promiseTest.then(()=>{
  // 성공했을때
}).then(()=>{
 // 성공했을때 (연달아서 사용 가능)
}).catch(()=>{
 // 실패했을때
})
```

## 2. 프로미스 예제1 조건문 사용하기
사실 프로미스는 예제 1번 틀을 확실히 이해한다면 다양한 예제를 만들어 사용할 수 있습니다.  
조건문을 사용해서 사용하는 법

```jsx
const promiseTest = new Promise((resolve, reject)=>{
  let isTrue = true
  if(isTrue){
    resolve()
  }else{
    reject()
  }
});

promiseTest.then(()=>{
  console.log('성공했습니다')
}).catch(()=>{
  console.log('실패했습니다.')
})
```
만약에 실패했습니다 출력하고 싶으면 조건문에 ! 낫연산자 붙여주기 (!isTrue) 혹은 resolve()랑 reject()위치 바꾸기

## 3. 프로미스 예제2 setTimeout 활용하기
별다를게 없습니다 프로미스의 기본적인 틀안에 `setTimeout()`를 사용한것 뿐입니다!

```jsx
const promiseTest = new Promise((resolve, reject)=>{
  setTimeout(()=>{
    let sum = 5+5
    if(sum === 9){
      resolve()
    }else{
      reject()
    }
  },1000);
});

promiseTest.then(()=>{
  console.log('성공했습니다')
}).catch(()=>{
  console.log('실패했습니다.')
})
```

## 4. 프로미스 예제3 인자로 데이터 전달하기
resolve나 reject에 인자에 데이터를 전달하여 출력 할수 있습니다. 호출할 인자의 작명은 자유롭게 해도 됩니다.  
주목해야 할 부분은 resolve와 reject의 인자에 데이터를 어떻게 전달했는지 콘솔창을 통해 확인합시다!!
```jsx
const promiseTest = new Promise((resolve, reject)=>{
  setTimeout(()=>{
    let sum = 5+5
    if(sum){
      resolve(sum)
    }else{
      reject(sum)
    }
  },1000);
});

promiseTest.then((dataSum)=>{
  console.log('성공했습니다',dataSum)
}).catch((dataSum)=>{
  console.log('실패했습니다.',dataSum)
})
```